server:
  port: 8989
  context-path: /maven2
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/future
    username: root
    password: root
    name: future
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: future.zwp.entity